"""add business_type and service keywords

Revision ID: 1a7887ad14c1
Revises: ecc99343d32e
Create Date: 2026-05-20 02:03:41.324006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a7887ad14c1'
down_revision = 'ecc99343d32e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_keyword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_keyword', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_keyword_keyword'), ['keyword'], unique=True)

    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.drop_column('business_type')

    with op.batch_alter_table('service_keyword', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_keyword_keyword'))

    op.drop_table('service_keyword')
    # ### end Alembic commands ###
