"""IDS CSV upload support

Revision ID: 4aa53d591b1b
Revises: add_product_specifications
Create Date: 2026-07-29 19:23:19.872204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aa53d591b1b'
down_revision = 'add_product_specifications'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=20), nullable=False, server_default=sa.text("'user'")))
        batch_op.add_column(sa.Column('source_reference', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('import_batch', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('data_quality_score', sa.SmallInteger(), nullable=True))
        batch_op.add_column(sa.Column('claimed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('google_category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('plus_code', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('landmark', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('google_image_url', sa.String(length=500), nullable=True))
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('source',
               existing_type=sa.String(length=20),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('google_image_url')
        batch_op.drop_column('landmark')
        batch_op.drop_column('plus_code')
        batch_op.drop_column('google_category')
        batch_op.drop_column('claimed_at')
        batch_op.drop_column('data_quality_score')
        batch_op.drop_column('import_batch')
        batch_op.drop_column('source_reference')
        batch_op.drop_column('source')

    # ### end Alembic commands ###
