"""Add verification OTP table

Revision ID: c661e00c1a62
Revises: 4aa53d591b1b
Create Date: 2026-08-11 11:45:33.604126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c661e00c1a62'
down_revision = '4aa53d591b1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_otp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('resend_available_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('attempts_count', sa.Integer(), nullable=False))
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_otp', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('attempts_count')
        batch_op.drop_column('resend_available_at')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
