"""Add AI tracking fields to Shop and Product models

Revision ID: e30c1da51ed8
Revises: c9e5fa2b7d11
Create Date: 2026-04-28 18:28:10.509387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e30c1da51ed8'
down_revision = 'c9e5fa2b7d11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_tag_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('ai_job_status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_description_generated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ai_job_status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.drop_column('ai_job_status')
        batch_op.drop_column('ai_description_generated')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('ai_job_status')
        batch_op.drop_column('ai_tag_hash')

    # ### end Alembic commands ###
