"""Add support models

Revision ID: e3ac2ef69307
Revises: f228fef07af0
Create Date: 2026-05-09 00:29:40.920213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ac2ef69307'
down_revision = 'f228fef07af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_conversation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_conversation_user_id'), ['user_id'], unique=False)

    op.create_table('support_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['support_conversation.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_message_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_message_sender_id'), ['sender_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_message_sender_id'))
        batch_op.drop_index(batch_op.f('ix_support_message_conversation_id'))

    op.drop_table('support_message')
    with op.batch_alter_table('support_conversation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_conversation_user_id'))

    op.drop_table('support_conversation')
    # ### end Alembic commands ###
