"""Update User model with enhanced fields and add AuthToken model

Revision ID: e798cd1da96e
Revises: 8a7d71d7ab84
Create Date: 2025-12-16 10:51:30.255822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e798cd1da96e'
down_revision = '8a7d71d7ab84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_token_token'), ['token'], unique=False)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('unique_category_name'), type_='unique')
        batch_op.create_unique_constraint('unique_category_name', ['name', 'parent_id', 'level'])
        batch_op.drop_column('type')

    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.alter_column('verification_status',
               existing_type=postgresql.ENUM('PENDING', 'UNDER_REVIEW', 'VERIFIED', 'REJECTED', 'SUSPENDED', name='verificationstatus'),
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('subscription_type',
               existing_type=postgresql.ENUM('USER', 'PRODUCT', 'SHOP', name='subscriptiontype'),
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('region', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('district', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('town', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_phone_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('phone_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_activity', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(batch_op.f('user_email_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('user_username_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)
        batch_op.drop_column('is_active')
        batch_op.drop_column('premium')
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('premium', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_phone'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_unique_constraint(batch_op.f('user_username_key'), ['username'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('user_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('last_activity')
        batch_op.drop_column('phone_verified_at')
        batch_op.drop_column('is_phone_verified')
        batch_op.drop_column('email_verified_at')
        batch_op.drop_column('is_email_verified')
        batch_op.drop_column('address')
        batch_op.drop_column('town')
        batch_op.drop_column('district')
        batch_op.drop_column('region')
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('status')

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('subscription_type',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('USER', 'PRODUCT', 'SHOP', name='subscriptiontype'),
               existing_nullable=False)

    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.alter_column('verification_status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('PENDING', 'UNDER_REVIEW', 'VERIFIED', 'REJECTED', 'SUSPENDED', name='verificationstatus'),
               existing_nullable=False)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', postgresql.ENUM('TRUNK', 'BRANCH', 'LEAF', name='categorytype'), autoincrement=False, nullable=False))
        batch_op.drop_constraint('unique_category_name', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('unique_category_name'), ['name', 'parent_id', 'type'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('level')

    with op.batch_alter_table('auth_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_token_token'))

    op.drop_table('auth_token')
    # ### end Alembic commands ###
