"""Add analytics and event tracking

Revision ID: ecc99343d32e
Revises: 7d285c2ceb7f
Create Date: 2026-05-19 23:16:21.167494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ecc99343d32e'
down_revision = '7d285c2ceb7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_user_id'), ['user_id'], unique=False)

    op.create_table('saved_search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_search', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_search_query'), ['query'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_search_user_id'), ['user_id'], unique=False)

    op.create_table('search_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_history_query'), ['query'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_history_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_search_history_query'))
        batch_op.drop_index(batch_op.f('ix_search_history_created_at'))

    op.drop_table('search_history')
    with op.batch_alter_table('saved_search', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_search_user_id'))
        batch_op.drop_index(batch_op.f('ix_saved_search_query'))

    op.drop_table('saved_search')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_event_type'))
        batch_op.drop_index(batch_op.f('ix_event_entity_type'))
        batch_op.drop_index(batch_op.f('ix_event_entity_id'))
        batch_op.drop_index(batch_op.f('ix_event_created_at'))

    op.drop_table('event')
    # ### end Alembic commands ###
